speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_feature: False

decoder_config:
  vocabulary: tamil_tech/vocabularies/tamil_new_vocab.txt
  target_vocab_size: 1024
  max_subword_length: 4
  blank_at_zero: True
  beam_width: 5
  norm_score: True

model_config:
  name: conformer
  subsampling:
    type: conv2d
    filters: 144
    kernel_size: 3
    strides: 2
  positional_encoding: sinusoid_concat
  dmodel: 144
  num_blocks: 16
  head_size: 36
  num_heads: 4
  mha_type: relmha
  kernel_size: 32
  fc_factor: 0.5
  dropout: 0.1
  embed_dim: 512
  embed_dropout: 0.0
  num_rnns: 1
  rnn_units: 320
  rnn_type: lstm
  layer_norm: True
  joint_dim: 1024

learning_config:
  augmentations:
    after:
      time_masking:
        num_masks: 10
        mask_factor: 100
        p_upperbound: 0.2
      freq_masking:
        num_masks: 1
        mask_factor: 27

  dataset_config:
    train_paths:
      - data/oslr_train.tsv
      - data/oslr_dev.tsv
      - data/oslr_test.tsv
    eval_paths:
      - data/oslr_dev.tsv
    test_paths:
      - data/oslr_test.tsv
    tfrecords_dir: null

  optimizer_config:
    warmup_steps: 40000
    beta1: 0.9
    beta2: 0.98
    epsilon: 1e-9

  running_config:
    batch_size: 12
    accumulation_steps: 1
    num_epochs: 25
    outdir: trained_models/tamil_conformer_S_updated_v1
    log_interval_steps: 300
    eval_interval_steps: 500
    save_interval_steps: 1000

link: "https://drive.google.com/file/d/1_b97ttSN2F4L263VskwXbEtCcMc_UPsb/view?usp=sharing"
file_id: "1_b97ttSN2F4L263VskwXbEtCcMc_UPsb"