speech_config:
  sample_rate: 16000
  frame_ms: 25
  stride_ms: 10
  num_feature_bins: 80
  feature_type: log_mel_spectrogram
  preemphasis: 0.97
  normalize_signal: True
  normalize_feature: True
  normalize_per_feature: False

decoder_config:
  vocabulary: vocabularies/tamil_new_vocab.txt
  target_vocab_size: 64
  max_subword_length: 4
  blank_at_zero: True
  beam_width: 3
  norm_score: True

model_config:
  name: conformer
  subsampling:
    type: conv2d
    filters: 144
    kernel_size: 3
    strides: 2
  positional_encoding: sinusoid
  dmodel: 144
  num_blocks: 8
  head_size: 36
  num_heads: 4
  mha_type: relmha
  kernel_size: 32
  fc_factor: 0.5
  dropout: 0.1
  embed_dim: 320
  embed_dropout: 0.05
  num_rnns: 1
  rnn_units: 320
  rnn_type: lstm
  layer_norm: True
  joint_dim: 320

learning_config:
  augmentations:
    after:
      time_masking:
        num_masks: 10
        mask_factor: 100
        p_upperbound: 0.05
      freq_masking:
        num_masks: 1
        mask_factor: 27

  dataset_config:
    train_paths:
      - data/oslr_train.tsv
    eval_paths:
      - data/oslr_dev.tsv
    test_paths:
      - data/oslr_test.tsv
    tfrecords_dir: null
    
  optimizer_config:
    warmup_steps: 10000
    beta1: 0.9
    beta2: 0.98
    epsilon: 1e-9
  
  running_config:
    batch_size: 16
    num_epochs: 22
    outdir: trained_models/tamil_conformer_S_v3
    log_interval_steps: 1000
    eval_interval_steps: 1000
    save_interval_steps: 2000
