version: '3'

services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - "5000:5000"
    expose:
      - 5000
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 13000M
        reservations:
          cpus: '2'
          memory: 12000M